dist: trusty
jdk: openjdk-17
language: java
services:
  - postgresql
  - docker
  before_install:
  - chmod +x mvnw
env:
  global:
        - COMMIT=${TRAVIS_COMMIT::7}

      script:
        - ./mvnw clean install -B

      after_success:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
        - export IMAGE_NAME=simpleapi/pus-repository
        - docker build -t $IMAGE_NAME:myapi/latest .
        - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
        - docker push $IMAGE_NAME:$TAG

      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: simpleapi-pus

