language: java
sudo: true
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
services:
  - postgresql
  - docker
env:
  global:
        - secure: "KVIzy1WBgHhin3sjk0leL/lz8nQeHb6KHzIg0Zc76EB9MwEg2hSqG1kUoRBAiOh4SiayxxciqwZbpXnB93m+zzUl8DRzhDdTuXqcv1XcyqX37wYRM6JbRmewcXT5uukJIvMK6HeHist7Moy3awkOB+fSytbMegnKqiRGcvrVqsmxfp9ArM0bOXsWn6DutJBszHv1WQ7lhd/YOyIxRPFZU2//spr4Wc/CRpWvjyxsuyKjtRHHYxQFtLqYpNjiGy0rq9OB/khwoZvA2Y01W5pS1nj9M76K3n8F1Y7R5wTEwaR8Uzb8GRz52sGKodqB1XCYhvhu/8Q0D3Z3Jtyj+XFCq7TKs6YBt+Vq5f0Eke/b0JkvUkU/h+Ea8uRJ5ouWSgWSq+jIt8k/tKvEbW5BBH8KbTs/hT5qqtpUm4SBpuXREXh2fTfCL7ZNf99LA3RDfix58AWrQ1NGMkMf2lx3KPXLz42+QC8i7vRIzRao9+lg7/Lu8ksOhlrV4TIqjJJpQpYfEcW35D6tndxCvUXYVAxhrguhnnnH5NXA1aOaivFqSB0zzWLrPeF04bGwOO2w30grqKdeIr6+1wIMn2oR16CIeDg8cb3bJVkER876HIetS3hQdRxfiZvR5OwLnm+dWMRpD4GDmXLY3EJUVzK/e7uuKxWPMOx6xD4GsjKQcjnS4Lw="
        - secure: "ae3mm+//kIvalmjB4iM401ZRmrwHVXk4H317q0aQykb9M49m463VsFjDAJaFCDTyxbzmXfke3z7AkkT6KCz7rIAmTyTE/SD1VU7EIDhPqoeUFP6e1pyht2BYTpfY7aQ24ltmyYEb9VvqxcIdeknSGjKkofBcQG4aG6lZvl51K1YFuHllhWGL1vZxGZ6n4/wl/MlzCbkdC2mMfdrlcZ3EAt/Hk9Gbp05rWsoNkMSQ4HdoyAAXRDft1gDAA5WbQOxCDu+i337RKlBmoM/fEe5pqHflyavwKq4wmpxMYpeXKHLdMIwrn45FYAJsBu15DLZ5JBgJS4Ujlld77Mwm2LD1U5SHxnPAVSUIspeJV7vAeZkS80d5Lxf7+Ix5gQt0wjUsfulIOz2K9GizJgXUEln4v/U2fxaLdkZTyykjRBjkn5vJVzFWmrI+K5fXmXq86sz+aspHFFMYMc9LHf6o/OOeB8FUqEktnihaIogp9AKYmsQrUoYeaJHadFkYwgU2E47PZ7jcQb1WyLNPASPyomSUIVGEqoaQ1LG0QBe+XWQ+UrJhXC5KjzgPjY3C+kTFRz1F0mk7JlhqT+MolXmE011P+rnm8kNDOCq+u43gYd3faSdCRDV2FrRwa09EXErVTsJWmgtkWySBSf3VkiNa5JEyhq6UmyTTuUgamkxq70uRDCo="
        - secure: "Y+Daji2IbILe2hsI0TTiiWzTuqK9wAvmw0uV0Aywi/RFdmWk958KX8y35YU6uAzH2MKBvXCAWQtn+q5eMFPNThWfDyLVPznFGEf562JTeWXmyNln0rPAi2iG8DLrd3aQcNUipfI25Albvf7WbQPTtBb79pQrswfizQ+DBNCPE9xv4jAndAxRyXuSe4vDQXvlZjfp+f2o8b2C/xZvsIAIaFYi/xsfSuFH8pNGB35mYEcED13kpDBe2CVMYbmlT1gSCh9N98Klyt8ONrMC5xZeVGhcnT/ahAiJelZOw2wor4su5g8NkeKtqRae+l2MJANGd37q0gfpeujcD3U+cjvXOb8Hw+yET86uwCjI0UIi4XLc9gG0K0UB3oBfuB33j0x/xkUGjUQhbDQ0rr7/+X+rfrq8GAHXFPbmEF80H1Sb/l2xipFcx+b/kO+Idua6cmKd5yzdmQGFfvTIa6x7APW60YOlr7FDFPVWApfyDYhhMFZIcZzVf/SvtbUQhrsMGZAcmEQQ5bGbJq81EPLQfuarpw38BFk1R4mH0R7CdOw1tjiADR02hRwwE4JvjNA8+hOTqXiB7NFFsScm2sYbPzua0AqvtXh2RVKFGYN4bnFP5uE16B3cDUkCoRJPB3TBCtmbp3Ys+auLZ/a75EfY3kDKci0qaWoTEfEelZdZZ3i2bws="
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=myapi/pus-repository
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: simpleapi-pus
