dist:  trusty
jdk: oraclejdk8
language: java
before_install:
  - chmod +x mvnw
services:
  - postgresql
  - docker
env:
    global:
        - secure: "YsC3qCV+hr+wlcpdiQpxzizQoKxfP9K9iySApCeyIBYyP3gQYAZhNRk0i481tGT57pq5Al9mmGT14zTftUPKLunM4TvLyJVFfRjIZsBYz3boaYBtfinI1kgkyU9giNbJT4dSadV7F/nLN2FyWyViBoygVMCsLshkW/iSDNBXv9o8nQHxsZg9/K8cVqbK/blldQRCKhn5UmkMU6KGaYMOM3g0UCm+wJyjdaKkiWWGnQkQup9qSYVzIA2M3FJy4pkOv7fpjgMS1hvl/zlQWlfSg7Cjh0P3PMoPA5LJXT1JCmk9yaS0IVL+Vafhhbfj2OGGrDJX6/UBoVlOAoz2ePbHEkAfBij+WojCAVWtjV93AaUDjiIcQAMe98xP1WIByjYuus6iW9f/UvpiHZcmJ4MulWtdUB1/+Mx5axDjxlKYpPy47dj0DEmyZvEKZzrC/Xh2pmtCwtAsEFS1ea9MtNGoYCXjuwAh6puY8VhEwcA4GzsmQYzZZVjGOfJeJT8O2hzD1RHhBN3tfBDH6cDAP6QCsU6C/LA4Ufu/+0HNiXLR8FAXIsAmGikCLrpY80HDpmclBoPh3hZuDax7jLLTUtSwZAdaoLmTKzm+QiXzjdeQNExhQMBc2s/+8v/f8fwD+svkzk0VXaHYGhWiftXFSrcDOTAdwV4Ju5Z/NKaElGJzyos="
        - secure: "TqrRdcWG1z/+C0GX9ZTa4q+A6X6wgjqZHOgvElaG0JzzMLt55paq9Y50Wp6V88SSMLqj8x4iXG5je0g7plaBmSoVnCfgAQ99gAjWu1WkMO/YBiTwegzBIg8GEagd1rHMFCN4V30IS0Y+NeBw7EwgfExMTT5j8dg8oh8Vm/Ec4Uy37TEMK6woUMg1ZdyQxLHeZP2QFByiMw3e6nt3rjGAf+0DREwGhxYCpmcit7ZMe7qOWSDRMgi4k9chaBDMdH6lMVji8Mqqm8Wk4Zosmqa9S322f7eIeOLiKBjtnUtN+Sulv1fJ7hywRWD4V6Q6/0FJ42PNvXS0/awaRlnhtcVveSJ4AS61iPkLZ1XhBCXWyP3p2erEclc5HuKOE4L1Ui/K2aYssuS/D7bpArPk0fPTGHHRRgXk/gFUvgA0bCTSzmYXEvjV4KuoURFFWfxnkVen0Oh3O9SdHtR67DQjovIMyQeZe4nmI/72rtCxDUQ8P1GUGqqmbNjodiCouuuJGsU+36dvxfyaCDCfgEGw6gvB+Q7CYL25wH0CIu0o4bXxgH52gf9owsgGGStfKwQqheE2u8LAfEd/fp1qcqA3qfeBE0MAB2cAyvSqAbz3c2zFFTVo/LPKhlmBeCiU0hp9JKw35DaBEvgW7MQrEld3GxefotAhdJnfrbaeJtQbdDLtU4E="
        - secure: "K9ROYuGByq72jqHSlUTdca6WLU554g1b0rlQ6iqKlJ4i0FQsppDz7ULqP4Dg5vFaEwpKKXQwzOoca7lLydFawzZqaXG3sOvLW37pinf/rpb3XLFyXYei/k4DynRvzz7VfjwWWN60pM7VmV356wWhDGUNCJX2uycyUztIVzCqStyLDuJ34NDMFOiG1mO5dOEdGaeRP1AFVCPFD/iwQ0qhc6EEWxPLu2hPN0w6pm9Z/fn82ZuI5/IfHzYvfqGrnhT2adv+1XP6ymPKu+FjMtQX5zgitseTK5ahB0pbQ/frcqLR1zt9LffJk7QqQRxbv06KpyF4HiRjyQCy4ze+jW64L+xyYfgb+VTaJvsnb/hkT2O6Y3J3/PpocfPp6XuKcNtTcQm9XC90lCXIDnz7sQpo0AKhyXzRMY5pqErjvcmKxGrLsaQ/0ojPV1mgchyR4H6KGlDiyzl5QIVqx/hliaJRChakVRAy7fn6wcFA0hAsEyKNvzuQtIAfMdAFnBPaGYTNWYrxFRuTrvmYmgwfQixtW7E6BJqB1nyXCXMWOWUzdpjcmjPq7xyB+auJN6k86itkuHNU0ZAEbBV1jltilEwOrLng6Vy5O11qObAutiNq30Hr4h3BS9eQogv0fJ/HtWbaNk6Hqu37nokPAGCUQakivbq2B+Ppq5O7ZdEABXI1AaE="
        - COMMIT=${TRAVIS_COMMIT::7}
    script:
      - ./mvnw clean install -B
    
    after_success:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - export TAG=latest
      - export IMAGE_NAME=simpleapi/pus-repository
      - docker build -t $IMAGE_NAME:latest .
      - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
      - docker push $IMAGE_NAME:$TAG
    
    deploy:
      provider: heroku
      api_key: $HEROKU_API_KEY
      app: simpleapi-pus
